# reload config
bind R source-file ~/.tmux.conf \; display "Config successfully reloaded"

# improve pane splitting to keep path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# increase time to input command after prefix
set -s escape-time 5

# make messages last longer
set -g display-time 4000

# to use prefix + : for tmux commands
set -g status-keys emacs

# remap prefix from C-b to C-a 
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# disable automatic naming
set-option -g allow-rename off

# increase buffer
set -g history-limit 50000

# change to 1 based index
set -g base-index 1
setw -g pane-base-index 1

set -g mouse on

# APPEARANCE

set -g status-position top


# PLUGINS
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'
set -g @rose_pine_directory 'on'

set -g @plugin '2kabhishek/tmux2k'
set -g @plugin '2kabhishek/tmux2k'

set -g @tmux2k-theme 'default'
set -g @tmux2k-show-powerline true
set -g @tmux2k-refresh-rate 5

set -g @tmux2k-left-plugins "session git cwd"
set -g @tmux2k-right-plugins "cpu ram battery network time"
set -g @tmux2k-window-list-alignment 'absolute-centre'

# Rosé Pine (main) palette aliases
set -g @tmux2k-white        '#e0def4'
set -g @tmux2k-dark-gray    '#26233a'
set -g @tmux2k-gray         '#26233a'
set -g @tmux2k-black        '#191724'

set -g @tmux2k-light-blue   '#9ccfd8'
set -g @tmux2k-blue         '#31748f'
set -g @tmux2k-dark-blue    '#524f67'

set -g @tmux2k-light-green  '#9ccfd8'
set -g @tmux2k-green        '#31748f'
set -g @tmux2k-dark-green   '#403d52'

set -g @tmux2k-light-orange '#ebbcba'
set -g @tmux2k-orange       '#f6c177'
set -g @tmux2k-dark-orange  '#524f67'

set -g @tmux2k-light-pink   '#ebbcba'
set -g @tmux2k-pink         '#eb6f92'
set -g @tmux2k-dark-pink    '#6e6a86'

set -g @tmux2k-light-purple '#c4a7e7'
set -g @tmux2k-purple       '#c4a7e7'
set -g @tmux2k-dark-purple  '#908caa'

set -g @tmux2k-light-red    '#eb6f92'
set -g @tmux2k-red          '#eb6f92'
set -g @tmux2k-dark-red     '#524f67'

set -g @tmux2k-light-yellow '#f6c177'
set -g @tmux2k-yellow       '#f6c177'
set -g @tmux2k-dark-yellow  '#6e6a86'

# UI colors
set -g @tmux2k-text                 '#e0def4'
set -g @tmux2k-bg-main              '#191724'
set -g @tmux2k-bg-alt               '#1f1d2e'
set -g @tmux2k-message-bg           '#26233a'
set -g @tmux2k-message-fg           '#e0def4'
set -g @tmux2k-pane-active-border   '#c4a7e7'
set -g @tmux2k-pane-active-border-bg '#191724'
set -g @tmux2k-pane-border          '#403d52'
set -g @tmux2k-prefix-highlight     '#eb6f92'

# Segment colors
set -g @tmux2k-session-colors     "purple black"
set -g @tmux2k-git-colors         "blue black"
set -g @tmux2k-cwd-colors         "light-pink black"
set -g @tmux2k-window-list-colors "black purple"
set -g @tmux2k-cpu-colors         "light-blue black"
set -g @tmux2k-ram-colors         "yellow black"
set -g @tmux2k-battery-colors     "red black"
set -g @tmux2k-network-colors     "light-purple black"
set -g @tmux2k-time-colors        "light-orange black"

# must be at bottom of file!
run '~/.tmux/plugins/tpm/tpm'
